#!/bin/sh -ex

PGSQL_VER=$(ls /etc/postgresql/)

# configure postgres to listen for remote connections
CONF=/etc/postgresql/$PGSQL_VER/main/postgresql.conf
sed --in-place "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" $CONF

# configure postgres to accept remote connections
cat >> /etc/postgresql/$PGSQL_VER/main/pg_hba.conf <<EOF
# Accept all IPv4 connections - CHANGE THIS!!!
host    all         all         0.0.0.0/0             md5
EOF

